### PR TITLE
Chore: Refactor marvel-module to introduce Kotlin - pt 2

### PR DESCRIPTION
**Pull request by FWStelian**
### :cop: Reviewers

@JcMinarro , @FWVlad , @FWStelian 
##IMPORTANT NOTE :## Review this PR by commit. Every commit is the refactor of a package and will make your life easier.

### :pushpin: References
* **Related pull-requests:** https://github.com/FutureWorkshops/FW-Android-Architecture/pull/17

### :tophat: What is the goal?
Continue from where the previous PR left off, in this one I refactor the View/Presentation layer, created new MVP base-classes and refactored Dagger, to work better with Kotlin.

### How is it being implemented?

1.  Changed the `MVP` base classes. With the new approach, there is no MvpContract, but only Mvp**View** interfaces. The presenters do not take in the View in the constructor, but attach to the View as soon as they are injected (`onCreate()`) and detach from the View when `onDestroy()` is called.
2. I changed the way `Dagger2` is used. Rather than using static methods e.g. `AndroidInjector.inject(this)` we now build our own Components, which are used as injectors. This results to a cleaner `Application.class` and cleaner `Modules` as we no longer need all the library provided statics.
3. Added `Kotlin-android-extensions` and removed `ButterKnife`

### CODE REVIEW

**Comment by FWStelian** [comment]
PR moved from https://github.com/FutureWorkshops/FW-Android-Architecture/pull/20

**Comment by FWDimitrios** [comment]
Continuing the discussion from the old repo:
@fwarisp the reason I removed DaggerAndroid, is that now the Dagger/DI parts of the app are much cleaner, simpler and understandable. Instead of relying to `@ContributesAndroidInjector` and statics like `AndroidInjector`, we are building our own components and using them for injecting. This leads to less boilerplate and helps the developer understand how Dagger works without "magic" from static classes. What do you think?

**Comment by fwarisp** [comment]
@FWDimitrios I do not actually like dagger-android. I understand the reasoning behind it (a class should not know how it is injected) but I think they've gone too far with the implementation...

I struggled a lot to learn "vanilla" dagger, and I've done cool stuff with scopes, subcomponents, and alternative dependency graphs for tests. With android-dagger, that doesn't give you direct access to the components, I feel that this power is taken away from me, or it's just too hard to find out how to do stuff (eg see my question on forum about how to make a fragment's subcomponent to be a child of the activity's subcomponent).

I would be happy to use "vanilla" dagger in a new project rather that dagger-android.

Btw what about the kotlin DI frameworks (or DI without frameworks)? Anyone has played around? @JcMinarro maybe?

**Comment by JcMinarro** [comment]
I have played really little with `Dagger-Android` but I know that it could help us to generalize the injections in a better way that is not possible in `Dagger2`. I started to use `Dagger2` when `Dagger` was deprecated, but I have not been never a fan of `Dagger2`. The only thing that I like about it was the compilation failure instead of the runtime failure as we had in `Dagger`, but the compilation errors are hard to understand. `Dagger2` gives us compilation error because it generates code instead of using reflection to build all the factories that it does under the hood. All that auto-generated code doesn't work fine (at least now)  with the gradle cache and the kapt plugin needed to generate it when we work with Kotlin. I'm starting to hate `Dagger2` very hard because it is starting to be a big library that doesn't give us enough benefit.

What about Kotlin? Well, Kotlin out of the box doesn't provide any DI Engine, but there are 2 very interesting projects about DI Engine with Kotlin. 
I am doing some trails with them but I don't have yet a winner on that case
The two projects that I'm talking about are:
-. Koin: https://github.com/Ekito/koin
-. Kodein: http://kodein.org/Kodein-DI/

**Pull request merged**
